// Calibo AI Academy Real Company Inventory Master Data
// Source: Stock_Register_AI Academy_Last update 23Jul2026.xlsx
// API Schema Preserved: Field names strictly adhere to approved API contracts.

export const REAL_COMPANY_CATEGORIES = [
  { id: 1, category_name: 'Bags', is_active: true },
  { id: 2, category_name: 'Branding', is_active: true },
  { id: 3, category_name: 'Diaries', is_active: true },
  { id: 4, category_name: 'Gifts', is_active: true },
  { id: 5, category_name: 'Goodies', is_active: true },
  { id: 6, category_name: 'Stationary', is_active: true },
  { id: 7, category_name: 'T Shirts', is_active: true },
];

export const REAL_COMPANY_ITEMS = [
  {
    id: 101,
    item_code: 'S101',
    item_name: 'Calibo Badges',
    category_id: 2,
    unit: 'PCS',
    minimum_level: 100,
    default_unit_cost: 10.00,
    is_active: true,
  },
  {
    id: 102,
    item_code: 'S102',
    item_name: 'Calibo Branded Folders',
    category_id: 2,
    unit: 'PCS',
    minimum_level: 50,
    default_unit_cost: 35.00,
    is_active: true,
  },
  {
    id: 103,
    item_code: 'S103',
    item_name: 'Calibo Hangings - 3x8',
    category_id: 2,
    unit: 'PCS',
    minimum_level: 10,
    default_unit_cost: 150.00,
    is_active: true,
  },
  {
    id: 104,
    item_code: 'S104',
    item_name: 'Calibo Hangings+ KL - 3x8',
    category_id: 2,
    unit: 'PCS',
    minimum_level: 5,
    default_unit_cost: 180.00,
    is_active: true,
  },
  {
    id: 105,
    item_code: 'S105',
    item_name: 'College Brouchures',
    category_id: 6,
    unit: 'PCS',
    minimum_level: 50,
    default_unit_cost: 200.00,
    is_active: true,
  },
  {
    id: 106,
    item_code: 'S106',
    item_name: 'Diaries+Pens',
    category_id: 3,
    unit: 'SET',
    minimum_level: 15,
    default_unit_cost: 120.00,
    is_active: true,
  },
  {
    id: 107,
    item_code: 'S107',
    item_name: 'Key Chains with Calibo Logo',
    category_id: 5,
    unit: 'PCS',
    minimum_level: 50,
    default_unit_cost: 35.00,
    is_active: true,
  },
  {
    id: 108,
    item_code: 'S108',
    item_name: 'Laptop Bags + Water Bottles',
    category_id: 1,
    unit: 'SET',
    minimum_level: 20,
    default_unit_cost: 650.00,
    is_active: true,
  },
  {
    id: 109,
    item_code: 'S109',
    item_name: 'Lepakshi Gifts',
    category_id: 4,
    unit: 'PCS',
    minimum_level: 5,
    default_unit_cost: 450.00,
    is_active: true,
  },
  {
    id: 110,
    item_code: 'S110',
    item_name: 'Staff T Shirts',
    category_id: 7,
    unit: 'PCS',
    minimum_level: 10,
    default_unit_cost: 250.00,
    is_active: true,
  },
  {
    id: 111,
    item_code: 'S111',
    item_name: 'Standees - Large - 3x8( Round Shaped)',
    category_id: 2,
    unit: 'PCS',
    minimum_level: 2,
    default_unit_cost: 1200.00,
    is_active: true,
  },
  {
    id: 112,
    item_code: 'S112',
    item_name: 'Standees - Large 3x8 + KL Branding',
    category_id: 2,
    unit: 'PCS',
    minimum_level: 2,
    default_unit_cost: 1350.00,
    is_active: true,
  },
  {
    id: 113,
    item_code: 'S113',
    item_name: 'Student Brouchures',
    category_id: 6,
    unit: 'PCS',
    minimum_level: 200,
    default_unit_cost: 9.00,
    is_active: true,
  },
  {
    id: 114,
    item_code: 'S114',
    item_name: 'Student T Shirts',
    category_id: 7,
    unit: 'PCS',
    minimum_level: 25,
    default_unit_cost: 220.00,
    is_active: true,
  },
  {
    id: 115,
    item_code: 'S115',
    item_name: 'Table stand Flags',
    category_id: 2,
    unit: 'PCS',
    minimum_level: 5,
    default_unit_cost: 150.00,
    is_active: true,
  },
  {
    id: 116,
    item_code: 'S116',
    item_name: 'USB Cables',
    category_id: 5,
    unit: 'PCS',
    minimum_level: 30,
    default_unit_cost: 80.00,
    is_active: true,
  },
  {
    id: 117,
    item_code: 'S117',
    item_name: 'Vendor T Shirts',
    category_id: 7,
    unit: 'PCS',
    minimum_level: 10,
    default_unit_cost: 220.00,
    is_active: true,
  },
];

export const REAL_COMPANY_LOCATIONS = [
  {
    id: 1,
    location_name: 'Vijayawada Hub',
    description: 'Central campus inventory warehouse & event distribution depot',
    is_active: true,
  },
  {
    id: 2,
    location_name: 'Vizag Hub',
    description: 'Regional campus branch store & student goodie dispatch site',
    is_active: true,
  },
];

export const REAL_COMPANY_SUPPLIERS = [
  {
    id: 1,
    supplier_name: 'Red Chariot',
    contact_person: 'Vendor Coordinator',
    phone: '+91 98480 12345',
    email: 'orders@redchariot.com',
    address: 'Branding & Merchandising Hub, Hyderabad',
    is_active: true,
  },
  {
    id: 2,
    supplier_name: 'Local Print (Vijayawada)',
    contact_person: 'Press Manager',
    phone: '+91 866 2541234',
    email: 'print@vja-localprint.in',
    address: 'Governorpet, Vijayawada',
    is_active: true,
  },
  {
    id: 3,
    supplier_name: 'Local Print (Vizag)',
    contact_person: 'Branch Manager',
    phone: '+91 891 2789123',
    email: 'vizag@localprint.in',
    address: 'Dwaraka Nagar, Visakhapatnam',
    is_active: true,
  },
  {
    id: 4,
    supplier_name: 'Subin P (Calibo Internal)',
    contact_person: 'Subin P',
    phone: '+91 99000 11223',
    email: 'subin.p@calibo.internal',
    address: 'Calibo AI Academy Central Operations',
    is_active: true,
  },
];
