// Static Mock Data for Stock Overview (/api/stock)
// Reuses real company records from companyInventoryData.js
// Business Rule: Stock Value = Available Quantity * WAC per Item + Location

export const MOCK_STOCK_OVERVIEW_DATA = [
  {
    id: 1,
    item_id: 101,
    item_code: 'S101',
    item_name: 'Calibo Badges',
    category_id: 2,
    category_name: 'Branding',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    available_quantity: 650,
    unit: 'PCS',
    wac: 10.00,
    stock_value: 6500.00,
    minimum_level: 100,
    status: 'In Stock',
    breakdown: {
      opening_stock: 0,
      inward: 700,
      outward: 490,
      returns: 440,
      adjustments: +20,
    },
  },
  {
    id: 2,
    item_id: 101,
    item_code: 'S101',
    item_name: 'Calibo Badges',
    category_id: 2,
    category_name: 'Branding',
    location_id: 2,
    location_name: 'Vizag Hub',
    available_quantity: 1000,
    unit: 'PCS',
    wac: 10.00,
    stock_value: 10000.00,
    minimum_level: 100,
    status: 'In Stock',
    breakdown: {
      opening_stock: 1000,
      inward: 0,
      outward: 0,
      returns: 0,
      adjustments: 0,
    },
  },
  {
    id: 3,
    item_id: 102,
    item_code: 'S102',
    item_name: 'Calibo Branded Folders',
    category_id: 2,
    category_name: 'Branding',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    available_quantity: 99,
    unit: 'PCS',
    wac: 35.00,
    stock_value: 3465.00,
    minimum_level: 50,
    status: 'In Stock',
    breakdown: {
      opening_stock: 0,
      inward: 150,
      outward: 51,
      returns: 0,
      adjustments: 0,
    },
  },
  {
    id: 4,
    item_id: 106,
    item_code: 'S106',
    item_name: 'Diaries+Pens',
    category_id: 3,
    category_name: 'Diaries',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    available_quantity: 7,
    unit: 'SET',
    wac: 120.00,
    stock_value: 840.00,
    minimum_level: 15,
    status: 'Low Stock',
    breakdown: {
      opening_stock: 0,
      inward: 15,
      outward: 8,
      returns: 2,
      adjustments: -2,
    },
  },
  {
    id: 5,
    item_id: 107,
    item_code: 'S107',
    item_name: 'Key Chains with Calibo Logo',
    category_id: 5,
    category_name: 'Goodies',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    available_quantity: 160,
    unit: 'PCS',
    wac: 35.00,
    stock_value: 5600.00,
    minimum_level: 50,
    status: 'In Stock',
    breakdown: {
      opening_stock: 0,
      inward: 200,
      outward: 40,
      returns: 0,
      adjustments: 0,
    },
  },
  {
    id: 6,
    item_id: 108,
    item_code: 'S108',
    item_name: 'Laptop Bags + Water Bottles',
    category_id: 1,
    category_name: 'Bags',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    available_quantity: 67,
    unit: 'SET',
    wac: 650.00,
    stock_value: 43550.00,
    minimum_level: 20,
    status: 'In Stock',
    breakdown: {
      opening_stock: 50,
      inward: 55,
      outward: 38,
      returns: 0,
      adjustments: 0,
    },
  },
  {
    id: 7,
    item_id: 108,
    item_code: 'S108',
    item_name: 'Laptop Bags + Water Bottles',
    category_id: 1,
    category_name: 'Bags',
    location_id: 2,
    location_name: 'Vizag Hub',
    available_quantity: 50,
    unit: 'SET',
    wac: 650.00,
    stock_value: 32500.00,
    minimum_level: 20,
    status: 'In Stock',
    breakdown: {
      opening_stock: 50,
      inward: 0,
      outward: 0,
      returns: 0,
      adjustments: 0,
    },
  },
  {
    id: 8,
    item_id: 109,
    item_code: 'S109',
    item_name: 'Lepakshi Gifts',
    category_id: 4,
    category_name: 'Gifts',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    available_quantity: 3,
    unit: 'PCS',
    wac: 450.00,
    stock_value: 1350.00,
    minimum_level: 5,
    status: 'Low Stock',
    breakdown: {
      opening_stock: 0,
      inward: 4,
      outward: 0,
      returns: 0,
      adjustments: -1,
    },
  },
  {
    id: 9,
    item_id: 110,
    item_code: 'S110',
    item_name: 'Staff T Shirts',
    category_id: 7,
    category_name: 'T Shirts',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    available_quantity: 1,
    unit: 'PCS',
    wac: 250.00,
    stock_value: 250.00,
    minimum_level: 10,
    status: 'Low Stock',
    breakdown: {
      opening_stock: 10,
      inward: 0,
      outward: 9,
      returns: 0,
      adjustments: 0,
    },
  },
  {
    id: 10,
    item_id: 114,
    item_code: 'S114',
    item_name: 'Student T Shirts',
    category_id: 7,
    category_name: 'T Shirts',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    available_quantity: 18,
    unit: 'PCS',
    wac: 220.00,
    stock_value: 3960.00,
    minimum_level: 25,
    status: 'Low Stock',
    breakdown: {
      opening_stock: 0,
      inward: 51,
      outward: 33,
      returns: 0,
      adjustments: 0,
    },
  },
  {
    id: 11,
    item_id: 116,
    item_code: 'S116',
    item_name: 'USB Cables',
    category_id: 5,
    category_name: 'Goodies',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    available_quantity: 124,
    unit: 'PCS',
    wac: 80.00,
    stock_value: 9920.00,
    minimum_level: 30,
    status: 'In Stock',
    breakdown: {
      opening_stock: 0,
      inward: 124,
      outward: 0,
      returns: 0,
      adjustments: 0,
    },
  },
  {
    id: 12,
    item_id: 117,
    item_code: 'S117',
    item_name: 'Vendor T Shirts',
    category_id: 7,
    category_name: 'T Shirts',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    available_quantity: 0,
    unit: 'PCS',
    wac: 220.00,
    stock_value: 0.00,
    minimum_level: 10,
    status: 'Out of Stock',
    breakdown: {
      opening_stock: 0,
      inward: 17,
      outward: 17,
      returns: 0,
      adjustments: 0,
    },
  },
];
