// Static Mock Data for Opening Stock Transactions (/api/transactions/opening-stock)

export const MOCK_OPENING_STOCK_DATA = [
  {
    id: 1,
    item_id: 108,
    item_code: 'S108',
    item_name: 'Laptop Bags + Water Bottles',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    quantity: 50,
    unit_cost: 650.00,
    opening_date: '2026-07-01',
    remarks: 'Initial baseline stock initialization',
    created_by: 'Admin User',
    status: 'Completed',
  },
  {
    id: 2,
    item_id: 110,
    item_code: 'S110',
    item_name: 'Staff T Shirts',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    quantity: 10,
    unit_cost: 250.00,
    opening_date: '2026-07-01',
    remarks: 'Opening inventory record',
    created_by: 'Admin User',
    status: 'Completed',
  },
  {
    id: 3,
    item_id: 116,
    item_code: 'S116',
    item_name: 'USB Cables',
    location_id: 2,
    location_name: 'Vizag Hub',
    quantity: 150,
    unit_cost: 80.00,
    opening_date: '2026-07-15',
    remarks: 'Vizag regional opening stock',
    created_by: 'Stock Manager',
    status: 'Completed',
  },
];
