// Static Mock Data for Distribution Records (/api/transactions/distribution)
// Note: Distribution is a DETAIL of Outward (Outward 1 -> Many Distributions).
// Distribution does NOT deduct stock and does NOT create a stock movement.

export const MOCK_DISTRIBUTION_DATA = [
  {
    id: 1,
    outward_id: 1,
    outward_no: 'OUT-2026-101',
    item_id: 108,
    item_code: 'S108',
    item_name: 'Laptop Bags + Water Bottles',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    quantity: 20,
    recipient: 'Student Batch A',
    batch: 'BATCH-2026-01',
    department: 'Computer Science',
    purpose: 'Post Payment Goodie Kit',
    distribution_date: '2026-07-06',
  },
  {
    id: 2,
    outward_id: 1,
    outward_no: 'OUT-2026-101',
    item_id: 108,
    item_code: 'S108',
    item_name: 'Laptop Bags + Water Bottles',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    quantity: 10,
    recipient: 'Student Batch B',
    batch: 'BATCH-2026-02',
    department: 'Data Science',
    purpose: 'Post Payment Goodie Kit',
    distribution_date: '2026-07-07',
  },
  {
    id: 3,
    outward_id: 2,
    outward_no: 'OUT-2026-102',
    item_id: 114,
    item_code: 'S114',
    item_name: 'Student T Shirts',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    quantity: 33,
    recipient: 'KL Event Volunteers',
    batch: 'VOL-KL-01',
    department: 'Admissions',
    purpose: 'Event Uniform',
    distribution_date: '2026-07-08',
  },
];
