// Static Mock Data for Inward Stock Transactions (/api/transactions/inward)

export const MOCK_INWARD_DATA = [
  {
    id: 1,
    inward_no: 'GRN-2026-001',
    item_id: 108,
    item_code: 'S108',
    item_name: 'Laptop Bags + Water Bottles',
    supplier_id: 4,
    supplier_name: 'Subin P (Calibo Internal)',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    quantity: 40,
    unit_cost: 650.00,
    total_cost: 26000.00,
    inward_date: '2026-07-02',
    remarks: 'Received via Subin P for RTIH event',
  },
  {
    id: 2,
    inward_no: 'GRN-2026-002',
    item_id: 107,
    item_code: 'S107',
    item_name: 'Key Chains with Calibo Logo',
    supplier_id: 2,
    supplier_name: 'Local Print (Vijayawada)',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    quantity: 200,
    unit_cost: 35.00,
    total_cost: 7000.00,
    inward_date: '2026-07-03',
    remarks: 'Batch order print cost Rs. 7000',
  },
  {
    id: 3,
    inward_no: 'GRN-2026-003',
    item_id: 113,
    item_code: 'S113',
    item_name: 'Student Brouchures',
    supplier_id: 2,
    supplier_name: 'Local Print (Vijayawada)',
    location_id: 1,
    location_name: 'Vijayawada Hub',
    quantity: 1500,
    unit_cost: 9.00,
    total_cost: 13500.00,
    inward_date: '2026-07-04',
    remarks: 'Print batch cost Rs. 13500',
  },
];
