"""initial_calibo_inventory_schema

Revision ID: 58bc214000cc
Revises: 
Create Date: 2026-09-04 17:51:21.149543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58bc214000cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('location_name')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_name', sa.String(length=150), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id'),
    sa.UniqueConstraint('supplier_name')
    )
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=30), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('minimum_level', sa.Integer(), nullable=False),
    sa.Column('default_unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('minimum_level >= 0', name='ck_items_minimum_level_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('ix_items_category_id', 'items', ['category_id'], unique=False)
    op.create_index(op.f('ix_items_item_code'), 'items', ['item_code'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('inward_transactions',
    sa.Column('inward_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inward_no', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('inward_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_inward_quantity_positive'),
    sa.CheckConstraint('total_cost >= 0', name='ck_inward_total_cost_non_negative'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_inward_unit_cost_non_negative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('inward_id'),
    sa.UniqueConstraint('inward_no')
    )
    op.create_index('ix_inward_item_loc_date', 'inward_transactions', ['item_id', 'location_id', 'inward_date'], unique=False)
    op.create_table('opening_stock',
    sa.Column('opening_stock_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('opening_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_opening_stock_quantity_positive'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_opening_stock_unit_cost_non_negative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('opening_stock_id')
    )
    op.create_index('ix_opening_stock_item_loc_date', 'opening_stock', ['item_id', 'location_id', 'opening_date'], unique=False)
    op.create_table('outward_transactions',
    sa.Column('outward_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('outward_no', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('issued_to', sa.String(length=150), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('outward_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_outward_quantity_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('outward_id'),
    sa.UniqueConstraint('outward_no')
    )
    op.create_index('ix_outward_item_loc_date', 'outward_transactions', ['item_id', 'location_id', 'outward_date'], unique=False)
    op.create_table('return_transactions',
    sa.Column('return_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_return_quantity_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('return_id')
    )
    op.create_index('ix_return_item_loc_date', 'return_transactions', ['item_id', 'location_id', 'return_date'], unique=False)
    op.create_table('stock_adjustments',
    sa.Column('adjustment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('adjustment_id')
    )
    op.create_index('ix_adjustment_item_loc_date', 'stock_adjustments', ['item_id', 'location_id', 'adjustment_date'], unique=False)
    op.create_table('stock_movements',
    sa.Column('movement_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('movement_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.CheckConstraint("movement_type IN ('OPENING', 'INWARD', 'OUTWARD', 'RETURN', 'ADJUSTMENT')", name='ck_stock_movements_type_valid'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('movement_id')
    )
    op.create_index('ix_stock_movements_item_loc_date', 'stock_movements', ['item_id', 'location_id', 'movement_date'], unique=False)
    op.create_table('distribution_transactions',
    sa.Column('distribution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('outward_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recipient', sa.String(length=150), nullable=True),
    sa.Column('batch', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('distribution_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_distribution_quantity_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['outward_id'], ['outward_transactions.outward_id'], ),
    sa.PrimaryKeyConstraint('distribution_id')
    )
    op.create_index('ix_distribution_item_loc_date', 'distribution_transactions', ['item_id', 'location_id', 'distribution_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_distribution_item_loc_date', table_name='distribution_transactions')
    op.drop_table('distribution_transactions')
    op.drop_index('ix_stock_movements_item_loc_date', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index('ix_adjustment_item_loc_date', table_name='stock_adjustments')
    op.drop_table('stock_adjustments')
    op.drop_index('ix_return_item_loc_date', table_name='return_transactions')
    op.drop_table('return_transactions')
    op.drop_index('ix_outward_item_loc_date', table_name='outward_transactions')
    op.drop_table('outward_transactions')
    op.drop_index('ix_opening_stock_item_loc_date', table_name='opening_stock')
    op.drop_table('opening_stock')
    op.drop_index('ix_inward_item_loc_date', table_name='inward_transactions')
    op.drop_table('inward_transactions')
    op.drop_table('users')
    op.drop_index(op.f('ix_items_item_code'), table_name='items')
    op.drop_index('ix_items_category_id', table_name='items')
    op.drop_table('items')
    op.drop_table('suppliers')
    op.drop_table('roles')
    op.drop_table('locations')
    op.drop_table('categories')
    # ### end Alembic commands ###
